### ISSUE TITLE
CI table has alignment issues

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/pmforest#11]
This has been an ongoing issue, that has been "patched", but has had no real solution. A lot of variables impact the alignment, including the number of lines entered in the `x_lab` **and** the `CI_label`. The most recent patch addressed multiple lines for the `CI_label`, but did not take the `x_lab` argument into account.

### Example with 2 lines in `CI_label` and 2 lines for `x_lab`:
![image](https://user-images.githubusercontent.com/18685116/155572119-6da32594-1c77-4b16-9753-b3cff40bdda2.png)

### Example with 2 lines in `CI_label` and 1 line for `x_lab`:
(Notice how the table does not line up with the graph. The misalignment gets worse as you move down the y-axis.)
![image](https://user-images.githubusercontent.com/18685116/155572174-b346570f-46d3-4c2d-8736-26ebc9eb3e2e.png)

I can further expand the alignment function to take this into account. However the code is already not ideal, and it might be a good idea to completely refactor that instead of patching it. Also probably worth noting that a patch would not be that simple in this case.

**Comment by barrettk** [comment]
@seth127 thoughts?

**Comment by seth127** [comment]
Capturing some thoughts from a conversation @barrettk and I had offline:

* We have had several requests for this, so I think it's worth tackling at some point.
* If it ends up being a semi-major refactor, that's fine. We have a decent test suite, so this shouldn't be too tough to make sure things don't break.
* Another key test will be when you change the size of the plot (easy to test manually with clicking "Zoom" in the plot window in Rstudio and making the resulting window bigger or smaller). Whatever solution we implement, let's make sure there are `vdiffr` tests that explicitly output bigger and smaller plots, to be sure the alignment still looks right.
