### ISSUE TITLE
Lower minor interval has wrong upper bound for multiple simulations

### ISSUE THREAD

**Issue by timwaterhouse** [metrumresearchgroup/pmforest#13]
The lower minor interval appears to be showing the `lo` and `mid` points instead of `lo` and `hi`.

```r
rawData <- readRDS(system.file(file.path("test-data", "plotDataEXP.RDS"), package = "pmforest"))
sumData <- 
  summarize_data(
    rawData %>% filter(LVL == "Moderate"), 
    value = stat,
    group = GROUP,
    group_level = LVL,
    replicate = nsim
  ) %>% 
  print()

# A tibble: 1 × 11
  group group_level mid_mid mid_lo mid_hi lo_mid lo_lo lo_hi hi_mid hi_lo hi_hi
  <chr> <chr>         <dbl>  <dbl>  <dbl>  <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl>
1 EGFR  Moderate      0.695  0.690  0.705  0.633 0.625 0.641  0.760 0.750 0.770

plot_forest(sumData, vline_intercept = 1)
```
![image](https://user-images.githubusercontent.com/19149867/156610884-4c4ed4da-5af5-4b98-8d0c-b7f30a006e90.png)

(top of the lower minor interval should be higher, up to 0.641)

I believe this is the culprit (`lo_mid` -> `lo_hi`): https://github.com/metrumresearchgroup/pmforest/blob/1dd55a72cdc6d8bd685bd6b8df030467bd61e57f/R/classicforest.R#L169

**Comment by barrettk** [comment]
Thanks so much for reporting this @timwaterhouse! The fix will be reflected in the next release (coming soon)
