### ISSUE TITLE
Deal with deprecation warnings

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/pmforest#26]
Two warnings show up under `devtools::test()`.  (The below output is on gh-24's 3c540df, but the relevant code is shared with main.)

### ggplot2 size deprecation

```
Warning (test-nsim-plot.R:23): Multiple simulations: Multiple simulations base test [PMF-PLOT-012]
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
Backtrace:
 1. ... %>% ...
      at test-nsim-plot.R:23:4
 2. pmforest::plot_forest(...)
      at magrittr/R/pipe.R:136:2
 3. pmforest:::forest_constructor(...)
      at pmforest/R/plot-forest.R:104:4
 5. pmforest (local) `<fn>`(...)
 6. ggplot2::geom_linerange(...)
      at pmforest/R/classicforest.R:163:6
 7. ggplot2::layer(...)
      at ggplot2/R/geom-linerange.r:73:2
 8. ggplot2:::deprecate_soft0(...)
      at ggplot2/R/layer.r:133:4
```

### tidyselect: external vector selection deprecation

```
Warning (test-nsim-plot.R:23): Multiple simulations: Multiple simulations base test [PMF-PLOT-012]
Using an external vector in selections was deprecated in tidyselect 1.1.0.
ℹ Please use `all_of()` or `any_of()` instead.
  # Was:
  data %>% select(replicate)

  # Now:
  data %>% select(all_of(replicate))

See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
Backtrace:
  1. ... %>% ...
       at test-nsim-plot.R:23:4
 11. dplyr:::group_by.data.frame(., across(c(replicate, all_of(groups))))
       at dplyr/R/group-by.r:103:2
 12. dplyr::group_by_prepare(.data, ..., .add = .add, caller_env = caller_env())
       at dplyr/R/group-by.r:108:2
 13. dplyr:::add_computed_columns(...)
       at dplyr/R/group-by.r:176:2
 15. dplyr:::mutate_cols(...)
       at dplyr/R/group-by.r:214:6
     ...
 27. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
       at tidyselect/R/eval-walk.R:83:2
 28. tidyselect:::eval_c(expr, data_mask, context_mask)
       at tidyselect/R/eval-walk.R:154:2
 29. tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
       at tidyselect/R/eval-c.R:15:2
 30. tidyselect:::walk_data_tree(new, data_mask, context_mask)
       at tidyselect/R/eval-c.R:33:4
 31. tidyselect:::eval_sym(expr, data_mask, context_mask)
       at tidyselect/R/eval-walk.R:154:2
```

See metrumresearchgroup/bbr#561 for an example of resolving this one.

---

- [X] tidyselect
   gh-27
- [ ] ggplot2

**Comment by barrettk** [comment]
Ahh just saw this. Im not sure we want to address the first one for quite a while. See [comment](https://github.com/metrumresearchgroup/pmforest/pull/25#issuecomment-1314344614)

**Comment by kyleam** [comment]
> Ahh just saw this. Im not sure we want to address the first one for quite a while. See [comment](https://github.com/metrumresearchgroup/pmforest/pull/25#issuecomment-1314344614)

Yes, as you mention there, any change should be made considering compatibility with older ggplot2 versions.

> We could add a `suppressWarnings()` in the meantime though

That's one option, though in my opinion it should be a last resort.  Glancing at pmforest's code, I think the only spots that are an issue are the `geom_linerange` calls.  I'd think you could define a custom kludge for older ggplot2's.  Something like:

<details>
<summary>patch</summary>

```diff
diff --git a/R/classicforest.R b/R/classicforest.R
index d69c527..593a96a 100644
--- a/R/classicforest.R
+++ b/R/classicforest.R
@@ -151,25 +151,25 @@ classicforest <- function(plotdata,
     if(jitter_reps){
       p1 <- p1 +
         geom_point(aes(x=lo_mid, color=factor(group)), position = position_nudge(y = 0.3), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = lo_lo, xmax = lo_hi, color=factor(group)),
-                       position = position_nudge(y = 0.3), size=0.7) +
+        linerange(data=plotdata, aes(xmin = lo_lo, xmax = lo_hi, color=factor(group)),
+                  position = position_nudge(y = 0.3), linewidth = 0.7) +
         geom_point(aes(x=hi_mid, color=factor(group)), position = position_nudge(y = 0.55), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = hi_lo, xmax = hi_hi, color=factor(group)),
-                       position = position_nudge(y = 0.55), size=0.7) +
+        linerange(data=plotdata, aes(xmin = hi_lo, xmax = hi_hi, color=factor(group)),
+                  position = position_nudge(y = 0.55), linewidth = 0.7) +
         geom_point(aes(x=mid_mid, color=factor(group)), position = position_nudge(y = 0.425), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = mid_lo, xmax = mid_hi, color=factor(group)),
-                       position = position_nudge(y = 0.425), size=0.7)
+        linerange(data=plotdata, aes(xmin = mid_lo, xmax = mid_hi, color=factor(group)),
+                  position = position_nudge(y = 0.425), linewidth = 0.7)
     }else{
       p1 <- p1 +
         geom_point(aes(x=lo_mid, color=factor(group)), position = position_nudge(y = 0.5), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = lo_lo, xmax = lo_hi, color=factor(group)),
-                       position = position_nudge(y = 0.5), size=0.7) +
+        linerange(data=plotdata, aes(xmin = lo_lo, xmax = lo_hi, color=factor(group)),
+                  position = position_nudge(y = 0.5), linewidth = 0.7) +
         geom_point(aes(x=hi_mid, color=factor(group)), position = position_nudge(y = 0.5), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = hi_lo, xmax = hi_hi, color=factor(group)),
-                       position = position_nudge(y = 0.5), size=0.7) +
+        linerange(data=plotdata, aes(xmin = hi_lo, xmax = hi_hi, color=factor(group)),
+                  position = position_nudge(y = 0.5), linewidth = 0.7) +
         geom_point(aes(x=mid_mid, color=factor(group)), position = position_nudge(y = 0.5), size=0.1) +
-        geom_linerange(data=plotdata, aes(xmin = mid_lo, xmax = mid_hi, color=factor(group)),
-                       position = position_nudge(y = 0.5), size=0.7)
+        linerange(data=plotdata, aes(xmin = mid_lo, xmax = mid_hi, color=factor(group)),
+                  position = position_nudge(y = 0.5), linewidth = 0.7)
     }
 
   }
@@ -213,3 +213,11 @@ classicforest <- function(plotdata,
 
   p2
 }
+
+if (utils::packageVersion("ggplot2") >= "3.4.0") {
+  linerange <- geom_linerange
+} else {
+  linerange <- function(..., linewidth = 0.5) {
+    geom_linerange(..., size = linewidth)
+  }
+}
```

</details>

---

And a loosely related note: some tests should probably skip if ggplot2 is older than 3.4.0 due to an unrelated `square -> butt` change that also came with 3.4.0.  You can spot these in the svg changes from gh-25.

**Comment by barrettk** [comment]
> And a loosely related note: some tests should probably skip if ggplot2 is older than 3.4.0 due to an unrelated `square -> butt` change that also came with 3.4.0. You can spot these in the svg changes from [gh-25](https://github.com/metrumresearchgroup/pmforest/pull/25).

Funny enough we actually skip almost all the tests on drone because vdiffr ends up generating different svgs. We only test the summary functions at the moment. I like your suggestion though, will open a separate PR to address that. Do you think we should leave this issue open or do anything else to make sure we dont forget to revisit this in a year or so?

**Comment by kyleam** [comment]
> I like your suggestion though, will open a separate PR to address that. 

It's unclear to me whether "your suggestion" is referring to my suggested kludge or my suggestion to skip certain tests when an older ggplot2 is around.

> Do you think we should leave this issue open or do anything else to make sure we dont forget to revisit this in a year or so?

In my view, this can be closed once users with a newer ggplot2 would no longer see the warning (so, e.g., if you add a kludge like I mentioned).  What are you referring to with "revisit"?  Are you talking about removing the kludge at some point down the road?  It's a bit hard to say when there's not a clear policy with how far back pmforest supports, but I think a comment alongside the kludge is sufficient.  Keeping it shouldn't really add any burden (and if it does, then that will surface the issue for revisiting).

**Comment by barrettk** [comment]
> It's unclear to me whether "your suggestion" is referring to my suggested kludge or my suggestion to skip certain tests when an older ggplot2 is around.

I meant the kludge. Skipping the tests was a moot point since we already skip all the plotting tests (we have to run devtools::test() before merging instead).

>In my view, this can be closed once users with a newer ggplot2 would no longer see the warning (so, e.g., if you add a kludge like I mentioned). What are you referring to with "revisit"? Are you talking about removing the kludge at some point down the road? It's a bit hard to say when there's not a clear policy with how far back pmforest supports, but I think a comment alongside the kludge is sufficient. Keeping it shouldn't really add any burden (and if it does, then that will surface the issue for revisiting).

Yeah I meant removing it at some point, and requiring that ggplot be greater than or equal to ggplot2 3.4.0 in the description file. I guess you're right that it doesnt really matter, I just figured Metrum might want to remove any kludge if possible. Sounds like we might as well close the issue after the latest PR is merged (havent made it yet, but will in a moment).

**Comment by kyleam** [comment]
> Skipping the tests was a moot point since we already skip all the plotting tests (we have to run devtools::test() before merging instead).

It's not about skipping it on Drone.  It's about skipping it for people running it on Metworx so that the tests don't fail (with an unclear error) if they happen to have an older ggplot2.
