### ISSUE TITLE
Additional formating options for CI table

### ISSUE THREAD

**Issue by oskarrgh** [metrumresearchgroup/pmforest#31]
Would be great if additional visualization of CI table layout including specification of number of digits and selection of parenthesis ( ), instead of [ ], could be supported directly from the plot script.

**Comment by barrettk** [comment]
Hi @oskarrgh, thanks for taking an interest in the package! 

You can actually change the number of digits in the latest development version. I provided a full example below using the test data provided with the package. You make a good point about the CI interval formatting though. To clarify, are you looking to be able to toggle between `(` **_or_** `[`? As in you don't plan on mixing the two types _within the same plot_ to differentiate between open and closed intervals?


## Specifying number of digits
### Example Setup
```r
dataDir <- system.file("test-data", package = "pmforest")
specDir <- file.path(dataDir, "spec")

specFile <- yspec::ys_load(file.path(specDir, 'analysis3.yml'))

all_labels <- yspec::ys_get_short(specFile, title_case = TRUE)
all_labels$EGFR <- 'Renal Function'
all_labels$CL <- 'CL (L/hr)'
all_labels$V2 <- 'V (L)'
plot_labels <- ggplot2::as_labeller(unlist(all_labels))

# Summarize Data
plotData <- readRDS(file.path(dataDir, "plotData.RDS"))
sumData <- plotData %>%
  summarize_data(
    value = stat,
    group = GROUP,
    metagroup = param,
    group_level = LVL
  )
```

### Plot with `digits = 2`
```r
plot_forest(data = sumData,
                       shaded_interval = c(0.8,1.25),
                       summary_label = plot_labels,
                       text_size = 3.5,
                       digits = 2,
                       vline_intercept = 1,
                       x_lab = "Fraction and 95% CI \nRelative to Reference",
                       CI_label = "Median [95% CI]",
                       caption = "The shaded area corresponds
                   to the interval (0.8, 1.25)",
                   plot_width = 8,
                   x_breaks = c(0.4,0.6, 0.8, 1, 1.2, 1.4,1.6),
                   x_limit = c(0.4,1.45),
                   ggplot_theme = theme_classic(),
                   shape_size = 2,
                   annotate_CI=T
    )
```
![image](https://github.com/metrumresearchgroup/pmforest/assets/18685116/e9393299-991c-42cf-811b-1012fc35329e)

### Plot with `digits = 4`
```r
plot_forest(data = sumData,
            shaded_interval = c(0.8,1.25),
            summary_label = plot_labels,
            text_size = 3.5,
            digits = 4,
            vline_intercept = 1,
            x_lab = "Fraction and 95% CI \nRelative to Reference",
            CI_label = "Median [95% CI]",
            caption = "The shaded area corresponds
                   to the interval (0.8, 1.25)",
            plot_width = 8,
            x_breaks = c(0.4,0.6, 0.8, 1, 1.2, 1.4,1.6),
            x_limit = c(0.4,1.45),
            ggplot_theme = theme_classic(),
            shape_size = 2,
            annotate_CI=T
)
```
![image](https://github.com/metrumresearchgroup/pmforest/assets/18685116/bf899140-014f-48bf-84b5-5fbea2446354)

**Comment by oskarrgh** [comment]
Thats great! Toggling between `(`and `[` is what I would be looking for. Since the output often ends up in reports (authored with different "housestyles"), this detailed level of customization adds great value.

**Comment by barrettk** [comment]
@oskarrgh FYI we are working on this [now](https://github.com/metrumresearchgroup/pmforest/pull/32). After it has been reviewed/merged the latest development version will have this functionality, though it's unclear whether it will appear on next [mpn snapshot](https://mpn.metworx.com/docs/packages/pmforest) at this stage
