### ISSUE TITLE
create develop branch?

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/pmforest#9]
Let's merge directly to `main` for the first couple minor releases because they might be fast and furious, but ideally by the time we put this on MPN we'll create a `develop` branch so that we only merge changes to `main` when we make a release.

# Also change when we do this

* update [README](https://github.com/metrumresearchgroup/pmforest/blob/main/README.Rmd#L35) to say "develop" instead of "main"
* update [README](https://github.com/metrumresearchgroup/pmforest/blob/main/README.Rmd#L29) with MPN snapshot date (for first available snapshot containing `pmforest`)

**Comment by kyleam** [comment]
I'd suggest holding off on doing anything aside from "main + short-lived topic branches" until you feel the need for something more complicated.  In particular, until you intend to simultaneously work on two releases (e.g., working on X.Y.Z+1 and X.Y+1.Z at the same time).

**Comment by seth127** [comment]
probably a good move. We'll assess when we start building the next MPN, but I think you're probably right @kyleam that this issue may just loiter for awhile.
